export enum Metric {
  time,
  rows,
  cost,
  buffers,
  estimate_factor,
  io,
}

export enum BufferLocation {
  shared = "Shared",
  temp = "Temp",
  local = "Local",
}

export enum BufferType {
  hit = "Hit",
  read = "Read",
  written = "Written",
  dirtied = "Dirtied",
}

export enum HighlightType {
  NONE = "none",
  DURATION = "duration",
  ROWS = "rows",
  COST = "cost",
}

export enum SortDirection {
  asc = "asc",
  desc = "desc",
}

export enum EstimateDirection {
  over = 1,
  under = 2,
  none = 3,
}

export enum CenterMode {
  center,
  visible,
  none,
}

export enum Property {
  ACTUAL_LOOPS = "Actual Loops",
  ACTUAL_ROWS = "Actual Rows",
  ACTUAL_ROWS_FRACTIONAL = "*Actual Rows Is Fractional",
  ACTUAL_ROWS_REVISED = "*Actual Rows Revised",
  ACTUAL_STARTUP_TIME = "Actual Startup Time",
  ACTUAL_TOTAL_TIME = "Actual Total Time",
  ALIAS = "Alias",
  AVERAGE_IO_READ_SPEED = "*I/O Read Speed",
  AVERAGE_IO_WRITE_SPEED = "*I/O Write Speed",
  AVERAGE_LOCAL_IO_READ_SPEED = "*Local I/O Read Speed",
  AVERAGE_LOCAL_IO_WRITE_SPEED = "*Local I/O Write Speed",
  AVERAGE_SHARED_IO_READ_SPEED = "*Shared I/O Read Speed",
  AVERAGE_SHARED_IO_WRITE_SPEED = "*Shared I/O Write Speed",
  AVERAGE_SORT_SPACE_USED = "Average Sort Space Used",
  AVERAGE_SUM_IO_READ_SPEED = "*I/O Read Time speed (all scopes)",
  AVERAGE_SUM_IO_WRITE_SPEED = "*I/O Write Time speed (all scopes)",
  AVERAGE_TEMP_IO_READ_SPEED = "*Temp I/O Read Speed",
  AVERAGE_TEMP_IO_WRITE_SPEED = "*Temp I/O Write Speed",
  CACHE_EVICTIONS = "Cache Evictions",
  CACHE_HITS = "Cache Hits",
  CACHE_KEY = "Cache Key",
  CACHE_MISSES = "Cache Misses",
  CACHE_MODE = "Cache Mode",
  CACHE_OVERFLOWS = "Cache Overflows",
  CTE_NAME = "CTE Name",
  CTE_SCAN = "CTE Scan",
  DISABLED = "Disabled",
  DISK_USAGE = "Disk Usage",
  EXCLUSIVE_AVERAGE_IO_READ_SPEED = "*I/O Read Speed (exclusive)",
  EXCLUSIVE_AVERAGE_IO_WRITE_SPEED = "*I/O Write Speed (exclusive)",
  EXCLUSIVE_AVERAGE_LOCAL_IO_READ_SPEED = "*Local I/O Read Speed (exclusive)",
  EXCLUSIVE_AVERAGE_LOCAL_IO_WRITE_SPEED = "*Local I/O Write Speed (exclusive)",
  EXCLUSIVE_AVERAGE_SHARED_IO_READ_SPEED = "*Shared I/O Read Speed (exclusive)",
  EXCLUSIVE_AVERAGE_SHARED_IO_WRITE_SPEED = "*Shared I/O Write Speed (exclusive)",
  EXCLUSIVE_AVERAGE_SUM_IO_READ_SPEED = "*I/O Read Time speed (exclusive, all scopes)",
  EXCLUSIVE_AVERAGE_SUM_IO_WRITE_SPEED = "*I/O Write Time speed (exclusive, all scopes)",
  EXCLUSIVE_AVERAGE_TEMP_IO_READ_SPEED = "*Temp I/O Read Speed (exclusive)",
  EXCLUSIVE_AVERAGE_TEMP_IO_WRITE_SPEED = "*Temp I/O Write Speed (exclusive)",
  EXCLUSIVE_COST = "*Cost (exclusive)",
  EXCLUSIVE_DURATION = "*Duration (exclusive)",
  EXCLUSIVE_IO_READ_TIME = "*I/O Read Time (exclusive)",
  EXCLUSIVE_IO_WRITE_TIME = "*I/O Write Time (exclusive)",
  EXCLUSIVE_LOCAL_DIRTIED_BLOCKS = "*Local Dirtied Blocks (exclusive)",
  EXCLUSIVE_LOCAL_HIT_BLOCKS = "*Local Hit Blocks (exclusive)",
  EXCLUSIVE_LOCAL_IO_READ_TIME = "*Local I/O Read Time (exclusive)",
  EXCLUSIVE_LOCAL_IO_WRITE_TIME = "*Local I/O Write Time (exclusive)",
  EXCLUSIVE_LOCAL_READ_BLOCKS = "*Local Read Blocks (exclusive)",
  EXCLUSIVE_LOCAL_WRITTEN_BLOCKS = "*Local Written Blocks (exclusive)",
  EXCLUSIVE_READ_BLOCKS = "*Read Blocks (exclusive)",
  EXCLUSIVE_SHARED_DIRTIED_BLOCKS = "*Shared Dirtied Blocks (exclusive)",
  EXCLUSIVE_SHARED_HIT_BLOCKS = "*Shared Hit Blocks (exclusive)",
  EXCLUSIVE_SHARED_IO_READ_TIME = "*Shared I/O Read Time (exclusive)",
  EXCLUSIVE_SHARED_IO_WRITE_TIME = "*Shared I/O Write Time (exclusive)",
  EXCLUSIVE_SHARED_READ_BLOCKS = "*Shared Read Blocks (exclusive)",
  EXCLUSIVE_SHARED_WRITTEN_BLOCKS = "*Shared Written Blocks (exclusive)",
  EXCLUSIVE_SUM_IO_READ_TIME = "*I/O Read Time (exclusive, all scopes)",
  EXCLUSIVE_SUM_IO_WRITE_TIME = "*I/O Write Time (exclusive, all scopes)",
  EXCLUSIVE_TEMP_IO_READ_TIME = "*Temp I/O Read Time (exclusive)",
  EXCLUSIVE_TEMP_IO_WRITE_TIME = "*Temp I/O Write Time (exclusive)",
  EXCLUSIVE_TEMP_READ_BLOCKS = "*Temp Read Blocks (exclusive)",
  EXCLUSIVE_TEMP_WRITTEN_BLOCKS = "*Temp Written Blocks (exclusive)",
  EXCLUSIVE_WRITTEN_BLOCKS = "*Written Blocks (exclusive)",
  FILTER = "Filter",
  FULL_SORT_GROUPS = "Full-sort Groups",
  FUNCTION_NAME = "Function Name",
  GROUP_COUNT = "Group Count",
  GROUP_KEY = "Group Key",
  HASHAGG_BATCHES = "HashAgg Batches",
  HASH_BATCHES = "Hash Batches",
  HASH_BUCKETS = "Hash Buckets",
  HASH_CONDITION = "Hash Cond",
  HEAP_FETCHES = "Heap Fetches",
  INDEX_NAME = "Index Name",
  IO_READ_TIME = "I/O Read Time",
  IO_WRITE_TIME = "I/O Write Time",
  JIT = "JIT",
  JOIN_TYPE = "Join Type",
  LOCAL_DIRTIED_BLOCKS = "Local Dirtied Blocks",
  LOCAL_HIT_BLOCKS = "Local Hit Blocks",
  LOCAL_IO_READ_TIME = "Local I/O Read Time",
  LOCAL_IO_WRITE_TIME = "Local I/O Write Time",
  LOCAL_READ_BLOCKS = "Local Read Blocks",
  LOCAL_WRITTEN_BLOCKS = "Local Written Blocks",
  MEMORY_ALLOCATED = "Memory Allocated",
  MEMORY_USED = "Memory Used",
  NODE_ID = "nodeId",
  NODE_TYPE = "Node Type",
  OPERATION = "Operation",
  ORIGINAL_HASH_BATCHES = "Original Hash Batches",
  ORIGINAL_HASH_BUCKETS = "Original Hash Buckets",
  OUTPUT = "Output",
  PARALLEL_AWARE = "Parallel Aware",
  PARENT_RELATIONSHIP = "Parent Relationship",
  PARTIAL_MODE = "Partial Mode",
  PEAK_MEMORY_USAGE = "Peak Memory Usage",
  PEAK_SORT_SPACE_USED = "Peak Sort Space Used",
  PEV_PLAN_TAG = "plan_",
  PLANNED_PARTITIONS = "Planned Partitions",
  PLANNER_ESTIMATE_DIRECTION = "*Planner Row Estimate Direction",
  PLANNER_ESTIMATE_FACTOR = "*Planner Row Estimate Factor",
  PLANS = "Plans",
  PLAN_ROWS = "Plan Rows",
  PLAN_ROWS_REVISED = "*Plan Rows Revised",
  PLAN_WIDTH = "Plan Width",
  PRESORTED_KEY = "Presorted Key",
  PRE_SORTED_GROUPS = "Pre-sorted Groups",
  READ_BLOCKS = "*Read Blocks",
  RECHECK_COND = "Recheck Cond",
  RELATION_NAME = "Relation Name",
  ROWS_REMOVED_BY_FILTER = "Rows Removed by Filter",
  ROWS_REMOVED_BY_FILTER_REVISED = "*Rows Removed by Filter",
  ROWS_REMOVED_BY_INDEX_RECHECK = "Rows Removed by Index Recheck",
  ROWS_REMOVED_BY_INDEX_RECHECK_REVISED = "*Rows Removed by Index Recheck",
  ROWS_REMOVED_BY_JOIN_FILTER = "Rows Removed by Join Filter",
  ROWS_REMOVED_BY_JOIN_FILTER_REVISED = "*Rows Removed by Join Filter",
  SCAN_DIRECTION = "Scan Direction",
  SCHEMA = "Schema",
  SERIALIZATION = "Serialization",
  SHARED_DIRTIED_BLOCKS = "Shared Dirtied Blocks",
  SHARED_HIT_BLOCKS = "Shared Hit Blocks",
  SHARED_IO_READ_TIME = "Shared I/O Read Time",
  SHARED_IO_WRITE_TIME = "Shared I/O Write Time",
  SHARED_READ_BLOCKS = "Shared Read Blocks",
  SHARED_WRITTEN_BLOCKS = "Shared Written Blocks",
  SORT_KEY = "Sort Key",
  SORT_METHOD = "Sort Method",
  SORT_METHODS_USED = "Sort Methods Used",
  SORT_SPACE_MEMORY = "Sort Space Memory",
  SORT_SPACE_TYPE = "Sort Space Type",
  SORT_SPACE_USED = "Sort Space Used",
  STARTUP_COST = "Startup Cost",
  STRATEGY = "Strategy",
  SUBPLAN_NAME = "Subplan Name",
  SUM_IO_READ_TIME = "*I/O Read Time (all scopes)",
  SUM_IO_WRITE_TIME = "*I/O Write Time (all scopes)",
  TEMP_IO_READ_TIME = "Temp I/O Read Time",
  TEMP_IO_WRITE_TIME = "Temp I/O Write Time",
  TEMP_READ_BLOCKS = "Temp Read Blocks",
  TEMP_WRITTEN_BLOCKS = "Temp Written Blocks",
  TOTAL_COST = "Total Cost",
  WAL_BYTES = "WAL Bytes",
  WAL_FPI = "WAL FPI",
  WAL_RECORDS = "WAL Records",
  WORKERS = "Workers",
  WORKERS_LAUNCHED = "Workers Launched",
  WORKERS_LAUNCHED_BY_GATHER = "*Workers Launched By Gather",
  WORKERS_PLANNED = "Workers Planned",
  WORKERS_PLANNED_BY_GATHER = "*Workers Planned By Gather",
  WORKER_NUMBER = "Worker Number",
  WRITTEN_BLOCKS = "*Written Blocks",
}

export function toProperty(key: string): typeof Property[keyof typeof Property] {
  if (!(key in Property)) {
    throw new Error(`"${key}" is not a valid Property key`)
  }
  return Property[key as keyof typeof Property]
}

export enum SortSpaceMemoryProp {
  AVERAGE_SORT_SPACE_USED = "Average Sort Space Used",
  PEAK_SORT_SPACE_USED = "Peak Sort Space Used",
}

export enum Scope {
  SHARED = "shared",
  LOCAL = "local",
  TEMP = "temp",
}
