# This workflow uploads pev2.html file to release assets

name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build 
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Create a copy (for legacy)
      run: cp dist-app/index.html dist-app/pev2.html
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist-app/pev2.html
          dist-app/index.html
        # To only send out release mails when the release 
        # notes have been manually added
        draft: true

